# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62caeeea628b0b0b0c671aeaeb9ac3a2715e6b2d045ecfee42efbb3c444d0c4f1227f2513b91a97e2f5a0ef2cb09c4a67f8af90fa46cb3320d92606f7a674918

test:
  secret_key_base: 66b7f39925ebe5127393b43772d6fb6734498bac1a7a83a5cab6015038e25a7fee9724433f5b57863a65f7141be0159b9ae4e84938e095b0c5e8c55b20c68e90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
